### ISSUE TITLE
How to include a photo?

### ISSUE THREAD

**Issue by saeed2402** [shahen94/react-native-image-fit#2]
Hi,
This looks very useful but there is no list of props of ImageViewer tag. How can I reference a picture in it? The sample provided doesn't seem to have anything like `source={require('./somePhoto.jpg')}` in it..

**Comment by shahen94** [comment]
Hi @saeed2402 .
Here is the propType validation
https://github.com/shahen94/react-native-image-fit/blob/master/lib/ImageViewer.js#L36

I'll add this prop into `REAMDE.md` example

**Comment by shahen94** [comment]
I'm going to close this issue since it's not a issue.
Feel free to reopen this if my answer will not help you.
Thanks !
